version: '3.4'

services:
  trainerhut.persons.webapi:
    image: ${DOCKER_REGISTRY-}luxclusifuserwebapi
    build:
      context: .
      dockerfile: luxclusif.user.webapi/Dockerfile
    networks: 
    - luxclusif-user-network 

  luxclusif-user-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd"
      POSTGRES_DB: "luxclusif.user"
    networks:
      - luxclusif-user-network
    volumes:
      - ./Local/pgdata:/var/lib/postgresql/data

  luxclusif-user-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@luxclusif.com"
      PGADMIN_DEFAULT_PASSWORD: "P@ssw0rd"
    networks:
      - luxclusif-user-network
    depends_on:
      - luxclusif-user-postgres

  luxclusif-user-schema:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.conf -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./Local/database/dev-data:/flyway/sql
      - ./Local/drivers:/flyway/drivers
      - ./Local/database/conf:/flyway/conf
    depends_on:
      - luxclusif-user-network
    networks:
      - luxclusif-user-network

  luxclusif-user-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./Local/rabbitmq/data/:/var/lib/rabbitmq/
        - ./Local/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - luxclusif-user-network

networks:
  luxclusif-user-network:
    driver: bridge